server {
    listen 80;

    location /api/usuarios  { proxy_pass http://ms-usuarios:8080;  }
    location /api/canchas   { proxy_pass http://ms-canchas:8080;   }
    location /api/reservas  { proxy_pass http://ms-reservas:8080;  }
    location /api/reportes  { proxy_pass http://ms-reportes:8080;  }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}